### ISSUE TITLE
GPU program failed to execute at ___ 

### ISSUE THREAD

**Issue by idigitopia** [Kaixhin/PlaNet#10]
Not sure if it is a driver problem on my end or a code bug. my other torch models train fine. so hard to say . . . . 

Attaching the output. 
  1%|█▎        | 6/1000 [00:00<?, ?it/s]
                      | 0/100 [00:00<?, ?it/s
 File "main.py", line 138, in <module>
    beliefs, prior_states, prior_means, prior_std_devs, posterior_states, posterior_means, posterior_std_devs = transition_model(init_state, actions[:-1], init_belief, bottle(encoder, (observations[1:], )), nonterminals[:-1])
  File "/MinicondaInstallation/envs/planet_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCBlas.cu:259

**Comment by Kaixhin** [comment]
Given that other people are running this code fine, I suspect that there is an issue with your PyTorch setup. Note that you do need the latest version of PyTorch (1.1). Doesn't look like a memory issue, but easy way to test is use a small batch size and chunk size. You can also find out if it is a CUDA issue by running with `--disable-cuda`. Otherwise probably best to post to the PyTorch discussion forums first.

**Comment by idigitopia** [comment]
must be some bug, I could not make it run in that server but ran just fine in another without any environment change. closing the issue. 

Thanks a lot.
