### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by princessofpillows** [Kaixhin/PlaNet#16]
Hi Kai,
Thank you for writing this implementation, I find it much easier to follow than the original paper implementation. I am currently trying to do my own implementation in Keras and have a couple code related questions if you don't mind answering.

Could you please explain what the bottle method does? I understand it takes a model and the tuple (beliefs, posterior_states) as input, but I don't understand whats going on inside the function itself.
Thanks again!

```
def bottle(f, x_tuple):
  x_sizes = tuple(map(lambda x: x.size(), x_tuple))
  y = f(*map(lambda x: x[0].view(x[1][0] * x[1][1], *x[1][2:]), zip(x_tuple, x_sizes)))
  y_size = y.size()
  return y.view(x_sizes[0][0], x_sizes[0][1], *y_size[1:])
```

**Comment by Kaixhin** [comment]
As the comment says, it `Wraps the input tuple for a function to process a time x batch x features sequence in batch x features (assumes one output)`. So it squishes time x batch into one (large) batch dimension to pass into a model, and then undoes this on the (assumed only single) output. Makes e.g. encoding all observations a single operation for an entire sequence, rather than having to process a batch one timestep at a time.
